<a href="https://colab.research.google.com/github/DigantaDantale/Python-Experiments-/blob/main/Exp8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir my_package

In [2]:
%%writefile my_package/__init__.py
# Empty file

Writing my_package/__init__.py


In [3]:
%%writefile my_package/module1.py

def check_prime(num):
  if num == 1:
    print("prime no")
    return
  if num==2 or num==3:
    print("prime no")
    return
  if num%2==0 or num%3==0:
    print("Not prime")
    return
  count=5
  for count in range(5,num,count+6):
    if (num % count) == 0 or ((num) % count+2==0):
      print("Not prime")
      return
  print("prime no")

def calculate_factorial(num):
  fact = 1
  if num > 0:
    for count in range(1, num + 1):
      fact *= count
    print("\nFactorial of ", num, " is", fact)
  elif num == 0:
    print("\nFactorial of 0 is 1")
  else:
    print("\nPlease enter a non-negative integer !")

Writing my_package/module1.py


In [4]:
%%writefile my_package/module2.py

def add(a, b):
   return a + b

def sub(a, b):
   return a - b

def mul(a, b):
   return a * b

def div(a, b):
   return a / b

Writing my_package/module2.py


In [5]:
from my_package import module1 as m

number = int(input("Enter number = "))
m.check_prime(number)
m.calculate_factorial(number)

Enter number = 2
prime no

Factorial of  2  is 2


In [6]:
from my_package import module2 as m

a, b = map(int, input("Enter two numbers: ").split())
print(m.add(a,b))
print(m.mul(a,b))

Enter two numbers: 34 54
88
1836


In [7]:
import numpy as np

a = np.arange(6)
print(a)

a = np.array([2,3,4])
print(a)

b = np.array([(1.5,2,3),(4,5,6)])
print(b)

c = np.array([(1.5,2,3),(4,5,6)], dtype=complex)
print(c)

a = np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

a = np.array([20,30,40,50])
b = np.arange(4)
print(a-b)

a = np.array([[-1,2,0,4],
              [4,-0.5,6,0],
              [2.6,0,7,8],
              [3,-7,4,2.0]])

a = a[:2, ::2]
print(a)

[0 1 2 3 4 5]
[2 3 4]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5+0.j 2. +0.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
15
[20 29 38 47]
[[-1.  0.]
 [ 4.  6.]]
